name: GodotFirebaseiOS
options:
  bundleIdPrefix: godot.firebase.ios
  minimumXcodeGenVersion: 2.34.0
packages:
  SwiftGodot:
    url: https://github.com/migueldeicaza/SwiftGodot.git
    revision: ead7bffc9546c1740678a36096282e1a811b7da6

targets:
  GodotFirebaseiOS:
    type: framework
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Sources
    dependencies:
      - package: SwiftGodot
        product: SwiftGodotRuntime
      - framework: ../firebase_sdk/AppAuth.xcframework
        embed: false
      - framework: ../firebase_sdk/AppCheckCore.xcframework
        embed: false
      - framework: ../firebase_sdk/FBLPromises.xcframework
        embed: false
      - framework: ../firebase_sdk/FirebaseABTesting.xcframework
        embed: false
      - framework: ../firebase_sdk/FirebaseAnalytics.xcframework
        embed: false
      - framework: ../firebase_sdk/FirebaseAppCheckInterop.xcframework
        embed: false
      - framework: ../firebase_sdk/FirebaseAuth.xcframework
        embed: false
      - framework: ../firebase_sdk/FirebaseAuthInterop.xcframework
        embed: false
      - framework: ../firebase_sdk/FirebaseCore.xcframework
        embed: false
      - framework: ../firebase_sdk/FirebaseCoreExtension.xcframework
        embed: false
      - framework: ../firebase_sdk/FirebaseCoreInternal.xcframework
        embed: false
      - framework: ../firebase_sdk/FirebaseDatabase.xcframework
        embed: false
      - framework: ../firebase_sdk/FirebaseFirestore.xcframework
        embed: false
      - framework: ../firebase_sdk/FirebaseFirestoreInternal.xcframework
        embed: false
      - framework: ../firebase_sdk/FirebaseInstallations.xcframework
        embed: false
      - framework: ../firebase_sdk/FirebaseMessaging.xcframework
        embed: false
      - framework: ../firebase_sdk/FirebaseMessagingInterop.xcframework
        embed: false
      - framework: ../firebase_sdk/FirebaseRemoteConfig.xcframework
        embed: false
      - framework: ../firebase_sdk/FirebaseRemoteConfigInterop.xcframework
        embed: false
      - framework: ../firebase_sdk/FirebaseSharedSwift.xcframework
        embed: false
      - framework: ../firebase_sdk/GTMAppAuth.xcframework
        embed: false
      - framework: ../firebase_sdk/GTMSessionFetcher.xcframework
        embed: false
      - framework: ../firebase_sdk/GoogleAppMeasurement.xcframework
        embed: false
      - framework: ../firebase_sdk/GoogleAppMeasurementIdentitySupport.xcframework
        embed: false
      - framework: ../firebase_sdk/GoogleDataTransport.xcframework
        embed: false
      - framework: ../firebase_sdk/GoogleSignIn.xcframework
        embed: false
      - framework: ../firebase_sdk/GoogleUtilities.xcframework
        embed: false
      - framework: ../firebase_sdk/RecaptchaInterop.xcframework
        embed: false
      - framework: ../firebase_sdk/absl.xcframework
        embed: false
      - framework: ../firebase_sdk/grpc.xcframework
        embed: false
      - framework: ../firebase_sdk/grpcpp.xcframework
        embed: false
      - framework: ../firebase_sdk/leveldb.xcframework
        embed: false
      - framework: ../firebase_sdk/nanopb.xcframework
        embed: false
      - framework: ../firebase_sdk/openssl_grpc.xcframework
        embed: false
    settings:
      base:
        PRODUCT_NAME: GodotFirebaseiOS
        PRODUCT_MODULE_NAME: GodotFirebaseiOS
        SWIFT_VERSION: "5.0"
        BUILD_LIBRARY_FOR_DISTRIBUTION: YES
        GENERATE_INFOPLIST_FILE: YES
        OTHER_SWIFT_FLAGS:
          - "-suppress-warnings"
          - "-Xfrontend"
          - "-internalize-at-link"
          - "-Xfrontend"
          - "-lto=llvm-full"
          - "-Xfrontend"
          - "-conditional-runtime-records"
        OTHER_LDFLAGS:
          - "$(inherited)"
          - "-ObjC"
          - "-Wl,-undefined,dynamic_lookup"
          - "-Xlinker"
          - "-dead_strip"
