name: GodotFirebaseiOS
options:
  bundleIdPrefix: godot.firebase.ios
  minimumXcodeGenVersion: 2.34.0
packages:
  SwiftGodot:
    url: https://github.com/migueldeicaza/SwiftGodot.git
    revision: ead7bffc9546c1740678a36096282e1a811b7da6

targets:
  GodotFirebaseiOS:
    type: framework
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Sources
    dependencies:
      - package: SwiftGodot
        product: SwiftGodotRuntime
        
    postBuildScripts:
      - script: |
          find ../firebase_sdk -name "*.bundle" -exec cp -R {} "$TARGET_BUILD_DIR/$UNLOCALIZED_RESOURCES_FOLDER_PATH/" \;
        name: Copy Firebase Bundles
    settings:
      base:
        PRODUCT_NAME: GodotFirebaseiOS
        PRODUCT_MODULE_NAME: GodotFirebaseiOS
        SWIFT_VERSION: "5.0"
        BUILD_LIBRARY_FOR_DISTRIBUTION: YES
        GENERATE_INFOPLIST_FILE: YES
        CLANG_MODULES_AUTOLINK: NO
        "FRAMEWORK_SEARCH_PATHS[sdk=iphoneos*]":
          - "$(inherited)"
          - "$(PROJECT_DIR)/../firebase_sdk/ios-arm64"
        "FRAMEWORK_SEARCH_PATHS[sdk=iphonesimulator*]":
          - "$(inherited)"
          - "$(PROJECT_DIR)/../firebase_sdk/ios-arm64_x86_64-simulator"
        OTHER_SWIFT_FLAGS:
          - "-suppress-warnings"
          - "-Xfrontend"
          - "-internalize-at-link"
          - "-Xfrontend"
          - "-lto=llvm-full"
          - "-Xfrontend"
          - "-conditional-runtime-records"
          - "-Xfrontend"
          - "-disable-all-autolinking"
        OTHER_LDFLAGS:
          - "$(inherited)"
          - "-ObjC"
          - "-Wl,-undefined,dynamic_lookup"
          - "-Xlinker"
          - "-dead_strip"
